### ISSUE TITLE
Request for source code and weights

### ISSUE THREAD

**Issue by benjamincham** [CIVA-Lab/DeepFTSG#1]
I read your paper and i would like to replicate your results and work.

Request for you to release the code and weights please (as mentioned in the paper). Would there be an estimated date to release please...? 

Thanks in-advance

**Comment by GaniRahmon** [comment]
Thank you for reading the paper. I will make sure the code and the weights are available by the end of the week.

**Comment by machinevisionbeans** [comment]
Thank you sir. Appreciate the kind effort and contribution.

**Comment by machinevisionbeans** [comment]
Hello @GaniRahmon,

I hope you're doing well. I understand you might be busy. 

It would be greatly appreciated if you could share the source code

**Comment by GaniRahmon** [comment]
Hi, @machinevisionbeans. Sorry, I was trying to fix the error that I encountered while uploading the weights. I did upload the source code so that you have a chance to look at it. However, I will upload the instructions and weight tomorrow.

**Comment by GaniRahmon** [comment]
The code and weights are added along with all instructions to follow to replicate the work.
