### ISSUE TITLE
Request for requirements.txt file and weights.pt files.

### ISSUE THREAD

**Issue by Aurjay** [CIVA-Lab/DeepFTSG#2]
I am trying to execute the code for my university thesis research and I am undergoing lots of dependency errors. So it would be great to have a requirements.txt file and pretrained weights.pt files.

A short description of how to obtain flux and bgs for CDNET to execute the code would also be super helpful. Thanks a ton.

**Comment by GaniRahmon** [comment]
Hi. I am working on it to make everything available in a couple of days.

**Comment by GaniRahmon** [comment]
Hi. The code and weight are uploaded along with all instructions and dependencies to create an environment.
